# Generated by Django 2.2.5 on 2019-12-31 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('questions_under', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.modules')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice', models.CharField(max_length=200)),
                ('second_choice', models.CharField(max_length=200)),
                ('third_choice', models.CharField(max_length=200)),
                ('fourth_choice', models.CharField(max_length=200)),
                ('answers_under', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.questions')),
            ],
        ),
    ]
