# Generated by Django 2.2.5 on 2019-12-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_answers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct_answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
