# Generated by Django 2.2.4 on 2020-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='gameId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
