# Generated by Django 2.2.4 on 2020-01-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200127_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='gameId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
