# Generated by Django 2.2.4 on 2020-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200128_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.IntegerField(null=True),
        ),
    ]
