# Generated by Django 2.2.4 on 2020-02-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200128_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='score_under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.modules'),
        ),
    ]
